version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-inventory-container
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-container
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

volumes:
  pgdata:
